# SPDX-FileCopyrightText: 2016-2026 Markus Katharina Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Mount points with checks to be created
  ansible.builtin.debug:
    msg: "{{ checker_disk_checks_mounts }}"

- name: Create disk check for each mount
  ansible.builtin.include_role:
    name: checker_check_disk
  vars:
    checker_check_disk_id: >-
      {{
        'root-disk' if item == '/' else
        'disk-' ~ (item | trim('/') | regex_replace('/', '-'))
      }}
    checker_check_disk_paths:
      - "{{ item }}"
  loop: "{{ checker_disk_checks_mounts }}"
