# SPDX-FileCopyrightText: 2016-2026 Markus Katharina Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: EUPL-1.2

repos:
  - repo: local
    hooks:
      - id: reuse
        name: reuse lint
        entry: reuse lint
        language: system
        pass_filenames: false
        always_run: true
      - id: ansible-lint
        name: ansible-lint
        entry: ansible-lint
        language: system
        pass_filenames: false
        always_run: true
