# SPDX-FileCopyrightText: 2016-2026 Markus Katharina Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Deploy checker to the current system
  hosts: localhost
  become: true
  roles:
    - role: checker
    - role: checker_system_checks
    - role: checker_disk_checks
    - role: checker_network_checks
    - role: checker_notify_alerta
    - deploy_deploy
    # - webhook_server
