# SPDX-FileCopyrightText: 2016-2026 Markus Katharina Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Deploy the RPS Deployment System for the current user account
  hosts: localhost
  vars:
    deploy_deploy_systemd_units_scope: user
    deploy_instance_scope: user
  roles:
    - deploy_deploy
    - deploy_test_ohai
    - deploy_test_fail
    - role: deploy_ansible_play
      deploy_ansible_play_instance_id: ohai
      deploy_ansible_play_git_repo: "{{ playbook_dir }}"
      deploy_ansible_play_import_playbook_filename: ohai.yaml
