# SPDX-FileCopyrightText: 2016-2026 Markus Katharina Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Import notify tasks
  ansible.builtin.import_tasks: notify.yaml
- name: Import systemd tasks
  ansible.builtin.import_tasks: systemd.yaml
