# SPDX-FileCopyrightText: 2016-2026 Markus Katharina Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
notify_alerta_api_alert_url: http://localhost:8080/api/alert
notify_alerta_api_key: "EUeDlg7Ro4tKlOMW5-v5nMnTa08F1atbRIvavs3-"
notify_alerta_environment: Development
