# SPDX-FileCopyrightText: 2016-2026 Markus Katharina Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Install Podman and DNS dependencies
  ansible.builtin.apt:
    name:
      - podman
      - dnsmasq
      - containernetworking-plugins
      - podman-compose
      - golang-github-containernetworking-plugin-dnsname
      - aardvark-dns
    state: present
    update_cache: true
    cache_valid_time: 3600
