# SPDX-FileCopyrightText: 2016-2026 Markus Katharina Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart webhook
  ansible.builtin.systemd:
    name: webhook
    state: restarted
