# SPDX-FileCopyrightText: 2016-2026 Markus Katharina Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
checker_check_ping_cmd: check_ping -H {{ check_ping_hostname }} -w 10,2% -c 20,5%
