# SPDX-FileCopyrightText: 2016-2026 Markus Katharina Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
# Filesystems to exclude by type
checker_disk_checks_excluded_filesystems:
  - tmpfs
  - devtmpfs
  - proc
  - sysfs
  - cgroup
  - devpts
  - securityfs
  - pstore
  - autofs
  - mqueue
  - debugfs
  - hugetlbfs
  - fusectl
  - nfs
  - nfs4
  - overlay

# Mount points to explicitly exclude
checker_disk_checks_excluded_mounts: []
# Minimum size in GB to monitor
checker_disk_checks_minimum_size_mb: 128

# Filter mounts and extract just the mountpoints
checker_disk_checks_mounts: >-
  {{
    ansible_facts.mounts
    | rejectattr('fstype', 'in', checker_disk_checks_excluded_filesystems)
    | selectattr('size_total', '>', (checker_disk_checks_minimum_size_mb * 1024 * 1024))
    | map(attribute='mount')
    | reject('in', checker_disk_checks_excluded_mounts)
    | list
  }}
